### ISSUE TITLE
Doesn't seem to install with python 3.7

### ISSUE THREAD

**Issue by fionntan** [theodi/data-sharing-abm-model#2]
Is python3.6 a necessity or will later python3 installations also work? I have python 3.7 installed

I ran:

```bash
conda env create -f environment_simulation.yaml
```

and all the dependent libraries seemed to install but got this

```bash
Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while installing package 'conda-forge::attrs-19.1.0-py_0'.
FileNotFoundError(2, "No such file or directory: '/miniconda3/envs/odi/bin/python3.6'")
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, "No such file or directory: '/miniconda3/envs/odi/bin/python3.6'")
```

**Comment by fionntan** [comment]
So obviously the issue is this in `environment_simulation.yaml`

```yaml
dependencies:
  - python=3.6
```

I'm going to change it to 

```yaml
dependencies:
  - python>=3.6
```

and see if that works. As it seems bad practice to rely on an 18 month old release of Python.

**Comment by fionntan** [comment]
All right. 3.7 doesn't work because of specific NumPy version specified. Guess we'll need to add to the documentation that this has been set up to work with only python 3.6

**Comment by lies-b** [comment]
I can run it by changing the environment yamls to python=3.7 and using the default conda channel, plus changing the numpy version. I will push that yaml.

Conda should install the latest version given the prefix, in this case 3.6.8. Python 3.6.8 was released last December so it isn't such an old release. There are some issues around numerical packages with the number 3.7 release which is why we stick with 3.6 for now.

**Comment by lies-b** [comment]
@fionntan Can you test whether you can install the environment using `environment_simulation_py37.yaml`? And whether you can run the simulation? If yes, I will close this issue.

**Comment by fionntan** [comment]
Yep installed 3.6 and it worked. 

Also tried `environment_simulation_py37.yaml` with 3.7 and it worked also. 

Got a lot of warnings for this though in both versions:

```
invalid value encountered in true_divide
```

But you can close the issue. 👍

**Comment by lies-b** [comment]
Great.

Those run-time warnings are totally fine - I get them too, but they're dealt with appropriately within the model.
